name: fami_tools
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI Stuffs
  material_symbols_icons: ^4.2873.0
  table_calendar: ^3.1.0
  hotkey_manager: ^0.2.3
  flutter_gutter: ^2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # number_pagination: ^1.1.0
  sqflite: ^2.4.1
  sqflite_common_ffi: any
  sqflite_common_ffi_web: any
  path: ^1.9.0

  # For templating
  jinja: ^0.6.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  file_picker: ^10.2.0
  filesystem_picker: ^4.0.0

  provider: ^6.1.2
  intl: ^0.20.2
  number_to_vietnamese_words: ^1.0.1+1
  pdf: ^3.11.3
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  yaml: ^3.1.3
  diacritic: ^0.1.6
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  permission_handler: ^12.0.1

  # Excel and CSV, PITA because of poor maintainance
  excel:
    git: https://github.com/justkawal/excel
  spreadsheet_decoder:
    git: https://github.com/BlockRen/spreadsheet_decoder
  csv: ^6.0.0

  # Riverpod
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  hooks_riverpod: ^3.0.0-dev.17
  riverpod: any
  pdfrx: ^2.2.7
  path_provider: ^2.1.5
  external_path: ^2.2.0
  archive: ^4.0.7
  xml: ^6.6.1
  pdf_combiner: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  custom_lint:
  source_gen:
  flutter_gen_runner:

  freezed: ^3.2.0
  json_serializable: ^6.9.0
  drift_dev: ^2.26.0

  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/texgyreheros-bolditalic.otf
    - assets/fonts/texgyreheros-bold.otf
    - assets/fonts/texgyreheroscn-bolditalic.otf
    - assets/fonts/texgyreheroscn-bold.otf
    - assets/fonts/texgyreheroscn-italic.otf
    - assets/fonts/texgyreheroscn-regular.otf
    - assets/fonts/texgyreheros-italic.otf
    - assets/fonts/texgyreheros-regular.otf
    - assets/fonts/texgyretermes-bolditalic.otf
    - assets/fonts/texgyretermes-bold.otf
    - assets/fonts/texgyretermes-italic.otf
    - assets/fonts/texgyretermes-regular.otf
    - assets/fonts/Times_New_Roman.ttf
    - assets/fonts/Times_New_Roman_Bold.ttf
    - assets/fonts/Times_New_Roman_Bold_Italic.ttf
    - assets/fonts/Times_New_Roman_Italic.ttf
    - assets/copy-pasta.yaml
    - assets/templates/phd-admission-record.docx
    - assets/templates/sample.docx

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
